server:
  port: 8081

spring:
  sql.init.mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/sud
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.format_sql: true