server:
  port: 8081

spring:
  sql.init.mode: always
  datasource:
#    url: jdbc:mysql://localhost:3306/sud
    url: jdbc:mariadb://localhost:3306/sud

    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true

  properties:
#    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.format_sql: true



